---
- name: "Create temporary directory"
  shell: mktemp -d
  register: tempdir

- name: "Download vagrant"
  get_url: 
    url={{ vagrant_url }} 
    dest={{ vagrant_dir_tmp }}/vagrant.deb 
    force=yes

- name: "Install vagrant"
  command: dpkg -i {{ vagrant_dir_tmp }}/vagrant.deb

- name: "Install vagrant-lxc plugin"
  shell: vagrant plugin install vagrant-lxc

- name: "Cleanup temporary directory"
  file: 
    name={{ tempdir.stdout }} 
    state=absent

- name: "Download wily lxc box"
  shell: "cd /tmp && wget -nc https://www.dropbox.com/s/5vexe5fjzozrcdg/vagrant-lxc-wily-amd64.box"
  ignore_errors: yes

- name: "Download xenial lxc box"
  shell: "cd /tmp && wget -nc https://www.dropbox.com/s/vfb15qcivvlsjlq/vagrant-lxc-xenial-amd64.box"
  ignore_errors: yes


- name: "Add wily lxc box"
  shell: "sudo runuser -l root -c 'vagrant box add -f wily /tmp/vagrant-lxc-wily-amd64.box && rm /tmp/vagrant-lxc-wily-amd64.box'"
  ignore_errors: yes

- name: "Add xenial lxc box"
  shell: "sudo runuser -l root -c 'vagrant box add -f xenial /tmp/vagrant-lxc-xenial-amd64.box && rm /tmp/vagrant-lxc-xenial-amd64.box'"
  ignore_errors: yes

- name: "Run vagrant-lxc"
  shell: "sudo runuser -l root -c 'cd /vagrant/vagrant-host/ && vagrant up'"
  ignore_errors: yes
