Vagrant.configure("2") do |config|

  config.vm.synced_folder "/ansible", "/ansible"
  config.vm.synced_folder "/artemis", "/artemis"
  config.vm.synced_folder "/devops-non-production", "/devops-non-production"
  config.vm.synced_folder "/terraform", "/terraform"

  config.vm.provision :shell, path: "../provisioners/init_lxc.sh", args: ["default"]

  config.vm.define "xenial" do |xenial|
    xenial.vm.box = "developerinlondon/ubuntu_lxc_xenial_x64"
    xenial.vm.provider :lxc do |lxc|
      lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
    end
    xenial.vm.provision :shell, path: "../provisioners/install_ansible.sh", args: ["default"]
  end

  config.vm.define "wily" do |wily|
    wily.vm.box = "developerinlondon/ubuntu_lxc_wily_x64"
    wily.vm.provider :lxc do |lxc|
      lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
    end
    wily.vm.provision :shell, path: "../provisioners/install_ansible.sh", args: ["default"]
  end
end
