# -*- mode: ruby -*-
# vi: set ft=ruby :

###################################################################################################

require 'yaml'
require 'pry'

###################################################################################################

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'lxc'

###################################################################################################

NODES_FILE = '../environments/vagrant-in-vagrant/nodes.yml'

###################################################################################################

def load_config( config_file)
  YAML.load_file(config_file)
end

###################################################################################################

nodes = load_config( NODES_FILE )

###################################################################################################

Vagrant.configure('2') do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = true
  config.hostmanager.include_offline = true

  nodes.each do |node|
    config.vm.define node[:name] do |config|

      config.vm.box = node[:box]
      config.vm.provision :hostmanager

      if node[:synced_folders]
        node[:synced_folders].to_a.each do |sfolder|
          config.vm.synced_folder sfolder[:host_dir], sfolder[:vm_dir] , disabled: sfolder[:disabled]
        end
      else
        config.vm.synced_folder '', '/vagrant', disabled: true
      end
      config.vm.provider 'lxc' do |lxc|
        lxc.customize 'cgroup.memory.limit_in_bytes', "#{node[:memory]}M"
        lxc.customize 'utsname', "#{node[:name]}"
      end
    end
  end
end
