Vagrant.configure("2") do |config|
  config.vm.define "xenial" do |xenial|
    xenial.vm.box = "developerinlondon/ubuntu_lxc_xenial_x64"
    xenial.vm.provider :lxc do |lxc|
      lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
    end
  end

  config.vm.define "wily" do |wily|
    wily.vm.box = "developerinlondon/ubuntu_lxc_wily_x64"
    wily.vm.provider :lxc do |lxc|
      lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
    end
  end
end
