---
- name: "Update apt cache."
  when:
    ansible_distribution == 'Ubuntu'
  apt:
    update_cache=yes
    cache_valid_time=600

- name: "Install LXC utils"
  when:
    ansible_distribution == 'Ubuntu'
  apt:
    pkg="{{ item }}"
    update_cache=yes
    state=present
  with_items:
    - lxc
  changed_when: False