---
- hosts: all
  gather_facts: yes
  become: true

  vars_files:
    - vars/local.yml

  roles:
    - { role: osupgrade, tags: [ 'osupgrade' ] }
    - { role: lxc, tags: [ 'lxc' ] }
    - { role: vagrant, tags: [ 'vagrant' ] }

  tags:
    - local



